
services:
  postgres:
    image: postgres:12-alpine
    container_name: meu_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - minha_rede
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  sistema:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: meu_sistema
    volumes:
      - ./backend:/home/node/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - minha_rede
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/company || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3

  my-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.ngx
    container_name: meunginx
    ports:
      - "8080:80"
    networks:
      - minha_rede
    depends_on:
      sistema:
        condition: service_healthy

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.front
  #   container_name: meu_frontend
  #   volumes:
  #     - ./frontend:/home/node/app
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     sistema:
  #       condition: service_healthy
  #   networks:
  #     - minha_rede
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:3001 || exit 1"]  # Verifica se o frontend está respondendo
  #     interval: 15s
  #     timeout: 5s
  #     retries: 3

networks:
  minha_rede:
    driver: bridge

volumes:
  postgres_data:
    driver: local
