version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    container_name: meu_postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: amauri
      POSTGRES_DB: sisten
    networks:
      - minha_rede
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência de dados

  sistema:
    build: .
    container_name: meu_sistema
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://amauri:1234@meu_postgres:5432/sisten
    depends_on:
      - postgres
    networks:
      - minha_rede
    command: ["./start.sh"]  # Usar o script start.sh para rodar migrações e iniciar a aplicação

networks:
  minha_rede:
    driver: bridge

volumes:
  postgres_data:
    driver: local
