# FROM node:18-alpine

# COPY start.sh /

# RUN chmod +x /start.sh

# USER node

# WORKDIR /home/node/app

# COPY package.json ./

# COPY . ./

# EXPOSE 3000

FROM node:18-alpine

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod +x ./start.sh

RUN sed -i 's/\r$//' ./start.sh

EXPOSE 3000

CMD ["sh", "./start.sh"]